services:
  - type: web
    name: telegram-bot
    env: docker
    repo: https://github.com/tomson20/Sales-bot--telegram
    branch: master
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PAYZE_API_KEY
        sync: false
      - key: PAYZE_MERCHANT_ID
        sync: false
    autoDeploy: true

  - type: web
    name: bot-pinger
    env: python
    repo: https://github.com/tomson20/Sales-bot--telegram
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: python pinger.py
    envVars:
      - key: BOT_URL
        sync: false
    autoDeploy: true

